<?php
/**
 * Dc_Slider
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Dc
 * @package    Dc_Slider
 * @copyright  Copyright (c) 2015 Damián Culotta. (http://www.damianculotta.com.ar/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($slider_type == Dc_Slider_Model_System_Config_Source_Plugin::BXSLIDER): ?>
    <div class="bxslider-container">
        <ul class="bxslider">
            <?php foreach($slides as $slide): ?>
                <li class="bxslide">
                <?php if ($slide->getUrl() != ""): ?>
                    <a href="<?php echo $slide->getUrl(); ?>">
                <?php endif; ?>
                <img width="<?php echo $width; ?>" src="<?php echo $this->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'media' . $slide->getFilename(); ?>" alt="<?php echo $slide->getName(); ?>" title="<?php echo $slide->getName(); ?>" />
                <?php if ($slide->getUrl() != ""): ?>
                    </a>
                <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <script>
        $j(function() {
            $j('.bxslider').bxSlider({
                mode: 'fade',
                adaptiveHeight: true
            });
        });
    </script>
<?php else: ?>
    <div class="slideshow-container">
        <ul class="slideshow">
            <?php foreach($slides as $slide): ?>
                <li>
                    <?php if ($slide->getUrl() != ""): ?>
                    <a href="<?php echo $slide->getUrl(); ?>">
                        <?php endif; ?>
                        <img width="<?php echo $width; ?>" height="<?php echo $height; ?>" src="<?php echo $this->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'media' . $slide->getFilename(); ?>" alt="<?php echo $slide->getName(); ?>" />
                        <?php if ($slide->getUrl() != ""): ?>
                    </a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    <div class="slideshow-pager">&nbsp;</div>
    <span class="slideshow-prev">&nbsp;</span> <span class="slideshow-next">&nbsp;</span></div>
<?php endif; ?>